global:
  scrape_interval: 1s
  evaluation_interval: 1s
rule_files:
  #- "first_rule.yml"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'node'
    static_configs:
    - targets: ['172.17.0.2:9100']